### ISSUE TITLE
Error trying to create a project based on clerk-utils template: coord with missing sha

### ISSUE THREAD

**Issue by jaydeesimon** [mentat-collective/Clerk-Utils#15]
Hello!

When I follow the instructions on [this page](https://github.com/mentat-collective/clerk-utils/tree/main/resources/clerk_utils/custom) to create a new project based on the `clerk-utils/custom` template, I get an error.

```
$ clojure -Sdeps '{:deps {io.github.mentat-collective/clerk-utils {:git/tag "v0.3.0"}}}' \
-Tnew create \
:template clerk-utils/custom \
:name myusername/my-notebook-project
Error building classpath. Library io.github.mentat-collective/clerk-utils has coord with missing sha
```

I tried referencing the sha of that tag directly and it worked.

```
$ clojure -Sdeps '{:deps {io.github.mentat-collective/clerk-utils {:git/sha "582c804b90086ab3d0ed31b3b4777df79bf0baa6"}}}' \
-Tnew create \
:template clerk-utils/custom \
:name jaydeesimon/test-project
Creating project from clerk-utils/custom in test-project
```

For reference:
```
$ clojure --version
Clojure CLI version 1.11.1.1208
```

In trying to debug this, I found I can turn on `GITLIBS_DEBUG=true`. Here's what happens when I do that in case this is helpful.
```
$ GITLIBS_DEBUG=true clojure -Sdeps '{:deps {io.github.mentat-collective/clerk-utils {:git/tag "v0.3.0"}}}' \                                  
-Tnew create \
:template clerk-utils/custom \
:name jaydeesimon/test-project     
git --git-dir /Users/jeffreysimon/.gitlibs/_repos/https/github.com/seancorfield/deps-new fetch --quiet --all --tags --prune
git --git-dir /Users/jeffreysimon/.gitlibs/_repos/https/github.com/seancorfield/deps-new tag --sort=v:refname
git --git-dir /Users/jeffreysimon/.gitlibs/_repos/https/github.com/seancorfield/deps-new rev-parse 48bf01edfa6a959a970d7dcab3d882a93607a7f6^{commit}
git --git-dir /Users/jeffreysimon/.gitlibs/_repos/https/github.com/seancorfield/deps-new rev-parse v0.5.0^{commit}
git --git-dir /Users/jeffreysimon/.gitlibs/_repos/https/github.com/mentat-collective/clerk-utils fetch --quiet --all --tags --prune
git --git-dir /Users/jeffreysimon/.gitlibs/_repos/https/github.com/mentat-collective/clerk-utils tag --sort=v:refname
Error building classpath. Library io.github.mentat-collective/clerk-utils has coord with missing sha
```

It looks like it is looking for a specific sha by executing these git queries and ultimately can't find it. The reason I think that is true is if I do a `GITLIBS_DEBUG=true` and reference the sha of the tag, it doesn't print any git commands. My interpretation is it didn't go down some path where it tried to search for it.

For example:

```
$ GITLIBS_DEBUG=true clojure -Sdeps '{:deps {io.github.mentat-collective/clerk-utils {:git/sha "582c804b90086ab3d0ed31b3b4777df79bf0baa6"}}}' \
-Tnew create \
:template clerk-utils/custom \
:name jaydeesimon/test-project2
Creating project from clerk-utils/custom in test-project2
```

Let me know if there's any info that would be useful here.

-Jeff

**Comment by sritchie** [comment]
Thank you for the report! I didn't realize that :git/tag wasn't enough by itself without an accompanying sha... I'll get the template instructions fixed up. Let me know if you run into other problems!

**Comment by jaydeesimon** [comment]
Ah that makes sense. I don't have much day-to-day experience with deps.edn/Clojure Deps and didn't realize that either. Learn something new every day. Thanks @sritchie.

**Comment by sritchie** [comment]
Okay, this should be fixed up!
