### ISSUE TITLE
Running: bb clerk-watch gives The system cannot find the file specified.

### ISSUE THREAD

**Issue by milelo** [mentat-collective/Clerk-Utils#27]
Running ` bb clerk-watch` from a clean repo-clone on Windows 11:

Running npm install...
Execution error (IOException) at java.lang.ProcessImpl/create (ProcessImpl.java:-2).
CreateProcess error=2, The system cannot find the file specified.

[clojure-2965595452258754054.edn.txt](https://github.com/mentat-collective/Clerk-Utils/files/10849313/clojure-2965595452258754054.edn.txt)

**Comment by sritchie** [comment]
@milelo thanks for the report! I don't have a windows machine, so it would be great if possible get a smaller repro together. It seems like the error is happening in this function. can we reproduce this issue by calling only the line that errors?

https://github.com/mentat-collective/Clerk-Utils/blob/main/src/mentat/clerk_utils/build/shadow.clj#L60-L82

**Comment by milelo** [comment]
> @milelo thanks for the report! I don't have a windows machine, so it would be great if possible get a smaller repro together. It seems like the error is happening in this function. can we reproduce this issue by calling only the line that errors?
> 
> https://github.com/mentat-collective/Clerk-Utils/blob/main/src/mentat/clerk_utils/build/shadow.clj#L60-L82

Ok thanks for the info. I mainly use ClojureScript so I'm not familiar with the new Clojure tooling but I'll take a look,
it may take some time.

**Comment by milelo** [comment]
Ok thanks @sritchie, it's building OK on Windows now:
I've changed "npm" to "npm.cmd":
https://github.com/mentat-collective/Clerk-Utils/blob/main/src/mentat/clerk_utils/build/shadow.clj#L80
See this example to how to detect windows etc:
https://github.com/borkdude/jayfu/blob/main/bb.edn
Info from this thread:
https://clojurians-log.clojureverse.org/babashka/2021-07-14

**Comment by sritchie** [comment]
Sounds great, I'll try and get to this this week; I'd also be happy to take a PR if you find some time.

**Comment by sritchie** [comment]
Closed by #30.
